### ISSUE TITLE
[doc]: outdated illustration in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/KCLVM#105]
Good CONTRIBUTING documentation, but there's an outdated introduction in ```Code Structure``` chapter: I can't find a ```spec``` file or directory anywhere in this repo.

**Comment by Peefy** [comment]
I will deprecate the `./CONTRIBUTING.md` and use `./docs/dev_guide/1.about_this_guide.md`
