### ISSUE TITLE
[Enhancement] KCL needs to have API to get configuration instance type.

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#174]
## Enhancement

What type of user's configuration is expected to be obtained in `Konfig`. 

Based on this, further fine-grained configuration checking or data statistics can be performed on the model used for use. For example, `projectA` uses `modelA`, and `projectB` uses `modelB`.

**Comment by amyXia1994** [comment]
#418 here are some other likely APIs requiring semantic information from KCLVM

**Comment by Peefy** [comment]
Closed by #471
