### ISSUE TITLE
[Enhancement] Use the GetSchemaType API to directly generate a Go struct from the KCL model and support Go struct to KCL schema

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#198]
## Reference

+ kcl-loader-rs: https://github.com/i-think-rapido/kcl-loader-rs
+ cuego: https://github.com/cue-lang/cue/tree/master/cuego
+ Go-cue conversion issue and PR in Kubevela
  + https://github.com/kubevela/kubevela/issues/5364
  + https://github.com/kubevela/kubevela/pull/5585
+ Support auto-generation of multiple languages SDK from CUE in Kubevela: https://github.com/kubevela/kubevela/issues/5365

**Comment by ekkoful** [comment]
@Peefy hello, I need to spend some time learning about this project.

**Comment by Peefy** [comment]
> @Peefy hello, I need to spend some time learning about this project.

Welcome! 👏. Glad to hear about your learning and design progress. If you have any questions, please feel free to communicate.
