### ISSUE TITLE
ld error on the latest macOS version 12.6

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#225]
## Bug Report

KCLVM runs with the error `stderr: ld: warning: -undefined dynamic_lookup may not work with chained fixups` on the latest macOS version 12.6 (including m1 and non-m1).

KCLVM version: v0.4.3

**Comment by CsBigDataHub** [comment]
FYI.. https://issues.guix.gnu.org/issue/57849

Looks like using `-Wl,-w` will help.

**Comment by zong-zhe** [comment]
> https://issues.guix.gnu.org/issue/57849

Thanks for your advice, it's helpful for us.

**Comment by zong-zhe** [comment]
Fixed in https://github.com/KusionStack/KCLVM/pull/234
