### ISSUE TITLE
[Bug] The error message output of CompilerBase is in a confused style

### ISSUE THREAD

**Issue by Peefy** [KusionStack/KCLVM#263]
![image](https://user-images.githubusercontent.com/22744597/198189285-94359bb8-7900-40d9-9217-85c87f78a9d3.png)

* The position of indicator '^' is wrong.
* The code separator '|' is in the wrong position.
* File location `file:line:column` appears twice.

**Comment by zong-zhe** [comment]
fixed. https://github.com/KusionStack/KCLVM/pull/354
