### ISSUE TITLE
build kclvm failed

### ISSUE THREAD

**Issue by errord** [KusionStack/KCLVM#286]
## Bug Report

./run.sh
1) build	  3) build-kclvm    5) test
2) build-cpython  4) update-kclvm   6) release

Please select the action: 1

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/1023682/200250124-2851b689-3e83-4627-b2bb-366120887ddf.png">

macos monterey 12.4

Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: arm64-apple-darwin21.5.0
Thread model: posix

**Comment by Peefy** [comment]
> ## Bug Report
> ./run.sh
> 
> 1. build	  3) build-kclvm    5) test
> 2. build-cpython  4) update-kclvm   6) release
> 
> Please select the action: 1
> 
> <img alt="image" width="1411" src="https://user-images.githubusercontent.com/1023682/200250124-2851b689-3e83-4627-b2bb-366120887ddf.png">
> 
> macos monterey 12.4
> 
> Apple clang version 13.0.0 (clang-1300.0.27.3) Target: arm64-apple-darwin21.5.0 Thread model: posix

Thank you for your feedback. It seems that this is a special case of the mac m1 (not replicated on our team's mac m1 computers). We need to take some time to replicate and solve this error.

**Comment by Peefy** [comment]
@errord We have made a external python3 deps to solve this issue. #288
