### ISSUE TITLE
The diagnostic information generated by CompilerBaseError needs to be optimized

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/KCLVM#292]
## Enhancement
- [ ] 1. The position of the underscore in the code snippet will be misplaced.
- [ ] 2. Code location information contains redundant end location.
- [ ] 3. The diagnostics for multiple lines of code are cluttered.
- [ ] 4. The number of digits in the line number at the beginning of each line will affect the typesetting.
- [ ] 5. There should be a space between the line number and the vertical bar.

**Comment by Peefy** [comment]
Related issue: #263
