### ISSUE TITLE
kclvm-runner build error.

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [KusionStack/KCLVM#323]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

environment：  
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

```$ llvm-config --libdir
/usr/local/lib
```

execute `cargo test --package kclvm-tools` 

### 3. What did you see instead (Required)

```Compiling kclvm-runner v0.1.0 (/root/KCLVM/kclvm/runner)
error: could not find native static library `lldMachO`, perhaps an -L flag is missing?

error: could not compile `kclvm-runner` due to previous error```
```

### 4. What is your KusionStack components version? (Required)

main branch

I found this line doesn't work in my environment. 

```println!("cargo:libdir={}", libdir);```

[/root/KCLVM/kclvm/runner/build.rs](https://github.com/KusionStack/KCLVM/blob/main/kclvm/runner/build.rs#L41)

when i change it to ```	println!("cargo:rustc-link-search={}", libdir); ```

I can build kclvm-runner successfully.

If needed， i can open a pr to solve it.

**Comment by Peefy** [comment]
Of course, you can open a PR to fix it directly. Thank you for your feedback. @my-vegetable-has-exploded

**Comment by my-vegetable-has-exploded** [comment]
I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy

**Comment by Peefy** [comment]
> I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy

@my-vegetable-has-exploded I have adjusted the LLVM version in the image to 13, and you can rerun CI.

**Comment by my-vegetable-has-exploded** [comment]
> > I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy
> 
> @my-vegetable-has-exploded I have adjusted the LLVM version in the image to 13, and you can rerun CI.

I found it still fails.  More details can be seen in these two ci [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6095474414) [build-and-test-ubuntu](https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095011064)

**Comment by Peefy** [comment]
> > > I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy
> > 
> > 
> > @my-vegetable-has-exploded I have adjusted the LLVM version in the image to 13, and you can rerun CI.
> 
> I found it still fails. More details can be seen in these two ci [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6095474414) [build-and-test-ubuntu](https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095011064)

@my-vegetable-has-exploded https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095961037 The main branch CI is normal, now U can open your PR please.

**Comment by my-vegetable-has-exploded** [comment]
> > > > I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy
> > > 
> > > 
> > > @my-vegetable-has-exploded I have adjusted the LLVM version in the image to 13, and you can rerun CI.
> > 
> > 
> > I found it still fails. More details can be seen in these two ci [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6095474414) [build-and-test-ubuntu](https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095011064)
> 
> @my-vegetable-has-exploded https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095961037 The main branch CI is normal, now U can open your PR please.
Sorry ， I can't reproduce the bug again now， there may be something wrong with my environment.  Sorry for taking up your time.

**Comment by my-vegetable-has-exploded** [comment]
> > > > I reran ci for the current main branch, but [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6087017595) failed. And I found the kclvm-builder container had been update 3days algo, and the version of lld/Common/Driver.h in the container maybe 14.x or 15.x not 12.x. I think that's maybe why this ci failed. @Peefy
> > > 
> > > 
> > > @my-vegetable-has-exploded I have adjusted the LLVM version in the image to 13, and you can rerun CI.
> > 
> > 
> > I found it still fails. More details can be seen in these two ci [build-and-test-ubuntu](https://github.com/my-vegetable-has-exploded/KCLVM/actions/runs/3612115650/jobs/6095474414) [build-and-test-ubuntu](https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095011064)
> 
> @my-vegetable-has-exploded https://github.com/KusionStack/KCLVM/actions/runs/3616626847/jobs/6095961037 The main branch CI is normal, now U can open your PR please.

Sorry ， I can't reproduce the bug again now， there may be something wrong with my environment. Sorry for taking up your time.
