### ISSUE TITLE
llvm-sys doesn't get compiled on ubuntu

### ISSUE THREAD

**Issue by thinkrapido** [KusionStack/KCLVM#397]
## Bug Report

error: could not find native static library `Polly`, perhaps an -L flag is missing?

error: could not compile `llvm-sys` due to previous error
warning: build failed, waiting for other jobs to finish...

It seams that inkwell is not compiling itself properly, becaus this crate imports llvm-sys

### 1. Minimal reproduce step (Required)

cargo build

### 2. What did you expect to see? (Required)

successful compilation

### 4. What is your KusionStack components version? (Required)

8ed4c5e (HEAD -> main, tag: v0.4.4, origin/main, origin/HEAD) Feat(kclvm-win): remove the "kclvm.requirements.done.txt" on windows. (#392)

**Comment by thinkrapido** [comment]
Maybe related https://github.com/wasmerio/wasmer/issues/2435

**Comment by Peefy** [comment]
@thinkrapido Would you please tell me your ubuntu version and LLVM version? KCLVM needs an LLVM-12 version. You can refer to the [development guide](https://github.com/KusionStack/KCLVM/blob/main/docs/dev_guide/2.quick_start.md).

**Comment by thinkrapido** [comment]
Ok, I solved it. I had not only to install libllvm but also clang
