### ISSUE TITLE
[Enhancement] KCL needs to provide API to list variables and attributes (including their name and type)

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/KCLVM#418]
## Enhancement

The KCL IDE extension needs many kinds of semantic information of the KCL files to provide visual and interactive support for users to modify their configurations quickly, without directly writing any code. 

- https://github.com/KusionStack/vscode-kusion/issues/10 describes image auto-update scenarios which requires `listVariable` and `overrideFile` API

- https://github.com/KusionStack/vscode-kcl/issues/12 describes low-code KCL init/modify/view scenarios which requires `listAttribute` API

**Comment by Peefy** [comment]
Related Issue: #174
