### ISSUE TITLE
feature: kclvm needs to know the mapping between the package name and the corresponding version of the package

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/KCLVM#491]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For multiple versions of kcl package, kclvm needs to know the mapping between the package name and the corresponding version of the package.

**Describe the feature you'd like:**

The mapping between the package name and version is passed in as an argument when running kclvm_cli.

```
kclvm_cli run main.k -E kcl1=xxx/xxx/xxx/kcl1_v0.0.1
```
In main.k
```
import kcl1 as k1
a = k1.k
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Peefy** [comment]
Close by #492
