### ISSUE TITLE
Python plugin functions not working after update kclvm to 0.4.6.1 version

### ISSUE THREAD

**Issue by harri2012** [KusionStack/KCLVM#534]
## Bug Report

Python plugin functions not working after update kclvm to 0.4.6.1 version.

### 1. Minimal reproduce step (Required)
a. create a source file `hello1.k`:
  ```
  import kcl_plugin.hello as hello
  abc = hello.tolower("ABC")
  ```
b. run the source file with command: `kcl hello1.k`, but output error.

### 2. What did you expect to see? (Required)
the file should run sucessfully, and output:
```
abc: abc
```

### 3. What did you see instead (Required)
 ```
 error[E3M38]: error[E3M38]: EvaluationError
 --> /home/dave/App/kclvm/plugins/hello/hello1.k:2:1
   |
2 | abc = hello.tolower("ABC")
   |  plugin is nil, should call kclvm_plugin_init at first
   |
 ```
### 4. What is your KusionStack components version? (Required)
kclvm version:   v0.4.6.1
`kclvm_cli version` output:  0.4.6-c5339e572207211e46477825e8aca903
`kcl --version` command not working after update from  v0.4.5 to v0.4.6.1

**Comment by Peefy** [comment]
Hello @harri2012, in the new version of KCL v0.4.6, as we are rethinking the design of Python Plugin, Python plugins are not enabled by default. You can refer to the [v0.4.6 version update documentation](https://kcl-lang.io/blog/2022-kcl-0.4.6-release-blog#other-updates-and-bug-fixes) and [python plugin documentation](https://kcl-lang.io/docs/reference/plugin/overview/) to enable and re-enable Python plugins.

**Comment by harri2012** [comment]
How to enable python plugin function?  The documents don't tell how to enable python plugin function.

**Comment by harri2012** [comment]
> How to enable python plugin function? The documents don't tell how to enable python plugin function.

I followed the [python plugin documentation](https://kcl-lang.io/docs/reference/plugin/overview/), put the plugins under folder: `$HOME/.kusion/kclvm/plugins`, and use command `python3 -m kclvm hello1.k`, now it works.

**Comment by harri2012** [comment]
the problem resolved
