### ISSUE TITLE
Enhancement: `LSP` needs to request `kpm` to get the path of external dependencies.

### ISSUE THREAD

**Issue by zong-zhe** [KusionStack/KCLVM#543]
## `LSP` needs to request `kpm` to get the path of external dependencies.
`kpm` will support command `kpm metadata` which returns the metadata includes the external dependency local path of the current kcl package. `LSP` can get the external package path from the metadata. 

[More information about `kpm metadata`](https://github.com/KusionStack/kpm/issues/66)

In the process of compiling, `LSP` will call `lookup_compile_unit()` to find the parts that need to be compiled. `lookup_compile_unit()` will return the files that need to be compiled and the compilation options.

Therefore, the process of executing `kpm metadata` to obtain the external package paths in method `lookup_compile_unit()`, and add the result to the compilation options to return.

```rust
// The pseudo code
fn lookup_compile_unit(
    file: &str,
    load_pkg: bool,
) -> (Vec<String>, Option<LoadProgramOptions>) {

        let opts := LoadProgramOptions::new();

        // 1. get 'kcl.mod' file path
        kcl_mod_path := lookup_kcl_mod_file(file)

        // 2. execute 'kpm metadata' under 'kcl.mod' file path
        metadata := Command.run("kpm", "metadata").under_dir(kcl_mod_path)

        // 3. fill the dependencies map in 'LoadProgramOptions'.
        fill_dependencies_map(metadata, opts)

        ......
}
```

**Comment by Peefy** [comment]
More consideration needs to be given to the abnormal situation of combining LSP and package management. After installing the kpm, the IDE automatically obtains the ability to do so.
